{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "kubor",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/deployments/kubor",
    "uid": "398048b4-953f-11e7-a046-080027896a56",
    "resourceVersion": "2611",
    "generation": 1,
    "creationTimestamp": "2017-09-09T09:14:03Z",
    "labels": {
      "app": "kubor"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "kubor"
      }
    },
    "template": {
      "metadata": {
        "name": "kubor",
        "creationTimestamp": null,
        "labels": {
          "app": "kubor"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "kubor",
            "image": "localhost:5000/kubor",
            "ports": [
              {
                "containerPort": 4000,
                "protocol": "TCP"
              }
            ],
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent",
            "securityContext": {
              "privileged": false
            }
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    }
  },
  "status": {
    "observedGeneration": 1,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2017-09-09T09:14:03Z",
        "lastTransitionTime": "2017-09-09T09:14:03Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}