apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubor
    spec:
      volumes:
      - name: kubor-pv-storage
        persistentVolumeClaim:
          claimName: kubor-pv-claim
      containers:
      - name: kubor
        image: localhost:5000/kubor:0.1.3
        ports:
        - containerPort: 4000
        volumeMounts:
        - mountPath: "/app/db/data"
          name: kubor-pv-storage
      #- name: kubectl
      #  image: localhost:5000/kubectl:v1.9.0-alpha.0.704
      #  args: ["proxy", "-p", "8001"]